name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get versions
      id: version
      run: |
        echo "major=$(awk -F, '{print $2}' .tags)" >> $GITHUB_OUTPUT
        echo "full=$(awk -F, '{print $1}' .tags)" >> $GITHUB_OUTPUT

    - name: Docker Setup qemu-action
      uses: docker/setup-qemu-action@v2
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1
    - name: DockerHub Login
      uses: docker/login-action@v2
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
        push: true
        tags: |
          ${{ github.repository }}:latest
          ${{ github.repository }}:${{ steps.version.outputs.full }}
          ${{ github.repository }}:${{ steps.version.outputs.major }}
